apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  selector:
    app: rabbitserver
  ports:
  - name: port1
    port: 5672
    targetPort: 5672
  - name: port2
    port: 15672
    targetPort: 15672
